"""Versionamento inicial

Revision ID: 42911cd3bcbf
Revises: 
Create Date: 2021-11-11 19:51:47.465092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42911cd3bcbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('info', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
